spring:
  application:
    name: spring-boot-webflux
  data:
    mongodb:
      database: moviesdb
      host: localhost
      port: 27017
# Puedes agregar aquí otras configuraciones, por ejemplo:
# server:
#   port: 8080
